# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "jobs", :force => true do |t|
    t.column "title",       :string
    t.column "name",        :string
    t.column "description", :text
    t.column "email",       :string
    t.column "created_at",  :date
  end

end
